/**
 * @file Types for the AI Scheduling and Recommendation Engine.
 * Defines the structures for suggestion contexts, task patterns,
 * wellbeing activities, and AI request/response payloads.
 */

// Import from parent types directory
import { Task, EnergyLevel } from '@/entities/task';
import { Category, Tag } from '@/entities/tag';
import { ContextSnapshot } from '@/entities/context';

// Re-export for convenience
export type { Task, EnergyLevel } from '@/entities/task';
export type { Category, Tag } from '@/entities/tag';
export type { ContextSnapshot } from '@/entities/context';
export type { UserVital } from '@/entities/vital';

// Types for AI Scheduling System

/**
 * Contextual data required by the recommendation engine to generate
 * personalized task suggestions.
 */
export interface SuggestionContext {
  currentTime: Date;
  energy: number; // 0-100 from dashboard
  tasks: Task[];
  tags: Tag[];
  completedTasks: Task[]; // Added for momentum tracking
  /** Optional pre-calculated last completed task for O(1) resolution. */
  lastTask?: Task;
  /** Optional pre-calculated active task ID set or map for O(1) blocking checks. */
  activeTaskIds?: Set<string> | Map<string, Task>;
}

/**
 * A recommendation generated by the system (either a specific task
 * or a wellbeing activity).
 */
export interface Suggestion {
  id: string;
  taskId?: string; // Added: Link to actual task entity
  type: 'task' | 'wellbeing';
  title: string;
  reason: string;
  priority: number; // 1-10, higher is more important
  estimatedDuration: number; // minutes
  category?: Category;
  energyRequirement?: EnergyLevel;
  isUrgent?: boolean;
  confidence: number; // 0-100, how confident we are in this suggestion
}

