/**
 * @file Types for the AI Scheduling and Recommendation Engine.
 * Defines the structures for suggestion contexts, task patterns,
 * wellbeing activities, and AI request/response payloads.
 */

// Import from parent types directory
import { TaskEntity, EnergyLevel } from '@/entities/task';
import { Category, Tag } from '@/entities/tag';
import { ContextSnapshot } from '@/entities/context';

// Re-export for convenience
export type { TaskEntity, EnergyLevel } from '@/entities/task';
export type { Category, Tag } from '@/entities/tag';
export type { ContextSnapshot } from '@/entities/context';
export type { UserVital } from '@/entities/vital';

// Types for AI Scheduling System

/**
 * Contextual data required by the recommendation engine to generate
 * personalized task suggestions.
 */
export interface SuggestionContext {
  currentTime: Date;
  energy: number; // 0-100 from dashboard
  availableMinutes: number;
  tasks: TaskEntity[];
  tags: Tag[];
  completedTasks: TaskEntity[]; // Added for momentum tracking
  backlogCount: number;
  userContext?: ContextSnapshot; // Added optional context
}

/**
 * A recommendation generated by the system (either a specific task
 * or a wellbeing activity).
 */
export interface Suggestion {
  id: string;
  taskId?: string; // Added: Link to actual task entity
  type: 'task' | 'wellbeing';
  title: string;
  reason: string;
  priority: number; // 1-10, higher is more important
  estimatedDuration: number; // minutes
  category?: Category;
  energyRequirement?: EnergyLevel;
  isUrgent?: boolean;
  confidence: number; // 0-100, how confident we are in this suggestion
}

