/**
 * @file Types for the AI Scheduling and Recommendation Engine.
 * Defines the structures for suggestion contexts, task patterns,
 * wellbeing activities, and AI request/response payloads.
 */

// Import from parent types directory
import { TaskEntity, EnergyLevel } from '@/entities/task';
import { Category, Tag } from '@/entities/tag';
import { ContextSnapshot } from '@/entities/context';
import { UserVital } from '@/entities/vital';

// Re-export for convenience
export type { TaskEntity, EnergyLevel } from '@/entities/task';
export type { Category, Tag } from '@/entities/tag';
export type { ContextSnapshot } from '@/entities/context';
export type { UserVital } from '@/entities/vital';

// Types for AI Scheduling System

/**
 * Contextual data required by the recommendation engine to generate
 * personalized task suggestions.
 */
export interface SuggestionContext {
  currentTime: Date;
  energy: number; // 0-100 from dashboard
  availableMinutes: number;
  tasks: TaskEntity[];
  tags: Tag[];
  completedTasks: TaskEntity[]; // Added for momentum tracking
  backlogCount: number;
  previousPatterns: TaskPattern[];
  userContext?: ContextSnapshot; // Added optional context
}

/**
 * Historical record of a task interaction, used for pattern recognition
 * and machine learning.
 */
export interface TaskPattern {
  taskCategory: Category;
  timeOfDay: number; // 0-23
  dayOfWeek: number; // 0-6 (Sunday-Saturday)
  energyLevel: number;
  completed: boolean;
  timestamp: number;
}

/**
 * A recommendation generated by the system (either a specific task
 * or a wellbeing activity).
 */
export interface Suggestion {
  id: string;
  taskId?: string; // Added: Link to actual task entity
  type: 'task' | 'wellbeing';
  title: string;
  reason: string;
  priority: number; // 1-10, higher is more important
  estimatedDuration: number; // minutes
  category?: Category;
  energyRequirement?: EnergyLevel;
  isUrgent?: boolean;
  confidence: number; // 0-100, how confident we are in this suggestion
}

/**
 * A non-task activity suggested to maintain user energy and focus.
 */
export interface WellbeingActivity {
  id: string;
  title: string;
  description: string;
  duration: number; // minutes
  category: 'Wellbeing';
  energyRequirement: 'Low';
  type: 'stretching' | 'breathing' | 'water' | 'walk' | 'meditation' | 'social';
}

export interface AIPredictionRequest {
  userEnergy: number;
  availableMinutes: number;
  urgentTaskCount: number;
  backlogCount: number;
  context: ContextSnapshot; // Added context to AI request
  recentPatterns: {
    preferredCategories: Category[];
    peakProductivityHours: number[];
    averageTaskDuration: number;
    completionRate: number;
  };
  topTasks: {
    title: string;
    category: Category;
    duration: number;
    energy: EnergyLevel;
    isUrgent: boolean;
  }[];
}

export interface AIPredictionResponse {
  suggestions: {
    task: string;
    reason: string;
    confidence: number;
  }[];
}
